apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  labels:
    app: shoppingclient  #for sevcice definitions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: todayisnowshopacr.azurecr.io/shoppingclient:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingapi-configmap
                  key: shoppingapi_url
          resources:
            requests:
                memory: "64Mi"
                cpu: "0.1"
            limits:
                memory: "128Mi"
                cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret          
        
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  type: LoadBalancer  #NodePort  
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      #nodePort: 30000